---

- name: enable plugin rabbit_management
  rabbitmq_plugin: 
    names: rabbitmq_management
    state: enabled
  when:
    - groups['controller'] | length  > 1

- name: Stop all Rabbitmq Services
  systemd: 
    name: rabbitmq-server
    state: stopped


- name: Set erlang_cookie
  command: cat /var/lib/rabbitmq/.erlang.cookie
  register: erlang_cookie
  run_once: yes

- name: Copy file erlang_cookie to other 
  copy: 
    dest: /var/lib/rabbitmq/.erlang.cookie
    content: "{{ erlang_cookie.stdout }}"
  delegate_to: "{{ item }}"
  with_items:   
    - "{{ groups['controller'] }}"
  run_once: yes

#- name: Sync file rabbitmq cookie
#  synchronize:
#    src: "{{ item }}"
#    dest: "{{ item }}"
#    mode: pull
#  delegate_to: "{{ groups['controller'][2] }}"
#  with_items:
#       - "/var/lib/rabbitmq/.erlang.cookie"
#      - "{{ groups['controller'][1] }}"
#      - "{{ groups['controller'][2] }}"
#  run_once: yes
#  when: cluster_status.stdout.find("rabbit@{{ inventory_hostname }}") == -1 

- name: Start all Rabbitmq Services
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- include_tasks: join_rabbitmq_cluster.yml
