---
- name: Start all Rabbitmq Services
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: enable plugin rabbit_management
  shell: rabbitmq-plugins enable rabbitmq_management
  when:
    - groups['controller'] | length  > 1

- name: Stop all Rabbitmq Services
  systemd: 
    name: rabbitmq-server
    state: stopped


#- name: backup old erlang cookie
#  shell: cp -a /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie.old
#  changed_when: false

- name: Config Erlang for controller2
  shell: scp -p  /var/lib/rabbitmq/.erlang.cookie  root@{{ hostvars[groups['controller'][1]]['ansible_' + MGNT_IF]['ipv4']['address'] }}:/var/lib/rabbitmq/.erlang.cookie
  when:
    - inventory_hostname_short == hostvars[groups['controller'][0]]['inventory_hostname_short']
    - groups['controller'] | length  > 1

- name: Config Erlang for controller3
  shell: scp -p  /var/lib/rabbitmq/.erlang.cookie  root@{{ hostvars[groups['controller'][2]]['ansible_' + MGNT_IF]['ipv4']['address'] }}:/var/lib/rabbitmq/.erlang.cookie
  when:
    - inventory_hostname_short == hostvars[groups['controller'][0]]['inventory_hostname_short']
    - groups['controller'] | length  > 1



#- name: check if erlang cookie changed and if it is so stopping server
#  template:
#    src: erlang.cookie.j2
#    dest: /var/lib/rabbitmq/.erlang.cookie.old
#    owner: rabbitmq
#    group: rabbitmq
#    mode: 0400

- name: Start all Rabbitmq Services
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

