---
- name: Start OpenvSwitch
  systemd:
    state: started
    enabled: true
    name: openvswitch

- name: Create OVS bridge
  openvswitch_bridge:
    bridge: br-provider
    state: present
    fail_mode: secure
  register: br_provider

- name: Add port for bridge
  openvswitch_port:
    bridge: br-provider
    port: "{{ FLAT_IF }}"
    state: present


- name: config FLAT interface
  template:
    src: ifcfgflat.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ FLAT_IF }}

- name: Check Bridge provider config
  stat: 
    path: /etc/sysconfig/network-scripts/ifcfg-br-provider
  register: br_provider


- name: Find Flat ip 
  set_fact:
    FLAT_IP: "{{ hostvars[inventory_hostname]['ansible_br_provider']['ipv4']['address'] }}"
  when:
    - br_provider.stat.exists
- name: Find Flat netmask
  set_fact:
    FLAT_NETMASK: "{{  hostvars[inventory_hostname]['ansible_br_provider']['ipv4']['netmask'] }}"
  when:
    - br_provider.stat.exists

    
- name: Config network bridge Provider
  template:
    src: ifcfg-br-provider.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-br-provider
  notify:
    - Restart network  

